spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.dev.os2iot.kmd.dk/realms/test-v1/protocol/openid-connect/certs

server:
  port: 9191

# Enable this for debugging
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
